# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170608_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDbDjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=4200, null=True)),
                ('state', models.CharField(blank=True, max_length=4200, null=True)),
                ('year', models.CharField(blank=True, max_length=4200, null=True)),
                ('quarter', models.CharField(blank=True, max_length=4200, null=True)),
                ('count', models.CharField(blank=True, max_length=4200, null=True)),
                ('households', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('hhincome_above_200k', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('average_rtl_price', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('price_per_watt', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('year_since_1990', models.FloatField(blank=True, null=True)),
                ('grid_to_panel_cost_ratio', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('net_metering', models.CharField(blank=True, max_length=42000, null=True)),
                ('net_metering_grade', models.CharField(blank=True, max_length=42, null=True)),
            ],
            options={
                'db_table': 'test-db-django',
                'managed': False,
            },
        ),
    ]
